### ISSUE TITLE
Errors when executing examples

### ISSUE THREAD

**Issue by barcode** [NVlabs/acronym#1]
I wanted to try your examples, but ran into a few problems:
(i am on Ubuntu 18 using Anaconda)

The error occurs when running your example for `acronym_visualize_grasps.py`

    $ acronym_visualize_grasps.py --mesh_root data/examples/ data/examples/grasps/Mug_10f6e09036350e92b3f21f1137c3c347_0.0002682457830986903.h5
    Traceback (most recent call last):
      File "/tmp/acronym-env/bin/acronym_visualize_grasps.py", line 7, in <module>
        exec(compile(f.read(), __file__, 'exec'))
      File "/tmp/acronym/scripts/acronym_visualize_grasps.py", line 31, in <module>
        from acronym_tools import load_mesh, load_grasps, create_gripper_marker
      File "/tmp/acronym/acronym_tools/__init__.py", line 24, in <module>
        from .acronym import *
      File "/tmp/acronym/acronym_tools/acronym.py", line 28, in <module>
        import trimesh.path
      File "/tmp/acronym-env/lib/python3.7/site-packages/trimesh/path/__init__.py", line 9, in <module>
        from .path import Path2D, Path3D
      File "/tmp/acronym-env/lib/python3.7/site-packages/trimesh/path/path.py", line 34, in <module>
        from . import polygons
      File "/tmp/acronym-env/lib/python3.7/site-packages/trimesh/path/polygons.py", line 3, in <module>
        from shapely import ops
    ModuleNotFoundError: No module named 'shapely'

it seems `shapely` is missing from your requirements.

After installing it with `pip install shapely` I get this error:

    Traceback (most recent call last):
      File "/tmp/acronym-env/bin/acronym_visualize_grasps.py", line 7, in <module>
        exec(compile(f.read(), __file__, 'exec'))
      File "/tmp/acronym/scripts/acronym_visualize_grasps.py", line 74, in <module>
        main()
      File "/tmp/acronym/scripts/acronym_visualize_grasps.py", line 55, in main
        obj_mesh = load_mesh(f, mesh_root_dir=args.mesh_root)
      File "/tmp/acronym/acronym_tools/acronym.py", line 375, in load_mesh
        obj_mesh = trimesh.load(os.path.join(mesh_root_dir, mesh_fname))
      File "/tmp/acronym-env/lib/python3.7/posixpath.py", line 94, in join
        genericpath._check_arg_types('join', a, *p)
      File "/tmp/acronym-env/lib/python3.7/genericpath.py", line 155, in _check_arg_types
        raise TypeError("Can't mix strings and bytes in path components") from None
    TypeError: Can't mix strings and bytes in path components

I get similar errors for your examples for `acronym_generate_scene.py` and `acronym_render_observations.py`

**Comment by clemense** [comment]
Great, thank you!
