### ISSUE TITLE
ValueError: string is not a file: data/examples/meshes/1Shelves/1e3df0ab57e8ca8587f357007f9e75d1.obj

### ISSUE THREAD

**Issue by huaji98** [NVlabs/acronym#11]
When the **ShapeNetSems** are unzipped, there is only the **Models** folder,so I run

python scripts/acronym_generate_scene.py --mesh_root models/ --objects grasps/1Shelves_1e3df0ab57e8ca8587f357007f9e75d1_0.011099225885734912.h5 grasps/1Shelves_1e3df0ab57e8ca8587f357007f9e75d1_0.011099225885734912.h5 --support data/examples/grasps/Table_99cf659ae2fe4b87b72437fd995483b_0.009700376721042367.h5 --show_grasps

than get

Traceback (most recent call last):
  File "/home/user/acronym/scripts/acronym_generate_scene.py", line 123, in <module>
    main()
  File "/home/user/acronym/scripts/acronym_generate_scene.py", line 73, in main
    object_meshes = [load_mesh(o, mesh_root_dir=args.mesh_root) for o in args.objects]
  File "/home/user/acronym/scripts/acronym_generate_scene.py", line 73, in <listcomp>
    object_meshes = [load_mesh(o, mesh_root_dir=args.mesh_root) for o in args.objects]
  File "/home/user/acronym/acronym_tools/acronym.py", line 375, in load_mesh
    obj_mesh = trimesh.load(os.path.join(mesh_root_dir, mesh_fname))
  File "/home/user/anaconda3/envs/acr/lib/python3.9/site-packages/trimesh/exchange/load.py", line 110, in load
    ) = parse_file_args(file_obj=file_obj,
  File "/home/user/anaconda3/envs/acr/lib/python3.9/site-packages/trimesh/exchange/load.py", line 605, in parse_file_args
    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: models/meshes/1Shelves/1e3df0ab57e8ca8587f357007f9e75d1.obj

**Was there a step I missed？**

![2021-10-13 08-08-42 的屏幕截图](https://user-images.githubusercontent.com/34676402/137045792-499e6e22-6457-4b34-b15c-bd9a1ec769a2.png)
![2021-10-13 08-08-56 的屏幕截图](https://user-images.githubusercontent.com/34676402/137045804-2c7cc7a3-d1f5-41c8-b02f-ea430ab3f27e.png)

**Comment by clemense** [comment]
What does `locate 1e3df0ab57e8ca8587f357007f9e75d1.obj` return?

**Comment by huaji98** [comment]
locate return:
/home/user/acronym/models/1e3df0ab57e8ca8587f357007f9e75d1.obj

and **shapenetsem** no subdirectory, for example '1Shelves' .
